// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rueikmnadfmundhonusm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1ZWlrbW5hZGZtdW5kaG9udXNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NzY0MDgsImV4cCI6MjA2NzE1MjQwOH0.D0uUaEk6MX90gESRwgHhWNsX_7L3VZ-U76c15He_DoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});